import "../../styles/globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import { Header } from "../components/header/page";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Tarefas+ | Organize suas tarefas de forma fácil",
  description: "Generated by sujeito Programador",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pt-br'>
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
